services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
  events-service:
    image: docker.io/library/events-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    ports:
      - '9000:9000'
  registration-service:
    image: docker.io/library/registration-service:0.0.1-SNAPSHOT
    depends_on:
      - mongo
      - events-service
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    ports:
      - '9001:9001'
