spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

